spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: jrtp
    url: jdbc:h2:mem:testdb
    username: jrtp
  jpa:
    properties:
      hibernate:
        show-sql: true
        defer-datasource-initialization: true